### ISSUE TITLE
Notebooks

### ISSUE THREAD

**Issue by jasonmcewen** [astro-informatics/s2scat#15]
- [x] Is the map consider in the notebooks actually a WL map or is it a transformed version?  We shouldn't be using transformed versions.
- [x] We should keep the current synthesis notebook but have another notebook that shows how to do a generation when using the function that wraps up most of the functionality in the current notebook.  See issue #13.
- [x] For the synthesis, we shouldn't start with saved down scattering covariances.  We should demonstrate computing these from an input map since that is what a user would need to do.
- [ ] We should include an example of how to work with a Healpix map.
- [ ] We should use the flm generation from s2fft in the synthesis notebook.
- [ ] Should we include an example of how to use the C backend?

**Comment by CosmoMatt** [comment]
closed by #18
